# Generated by Django 3.1.14 on 2024-08-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_auto_20240802_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(to='pokemon_entities.PokemonElementType'),
        ),
    ]
